### ISSUE TITLE
xi-roc-cafe uses older version of AlphaTwirl

### ISSUE THREAD

**Issue by benkrikler** [TaiSakuma/xi-roc-cafe#1]
I noticed that the alphatwirl used here is a few weeks behind the current version.

In particular, in [this line](https://github.com/TaiSakuma/xi-roc-cafe/blob/master/twirl_mktbl_heppy.py#L156) I think it should now read:
```
resultsCombinationMethod = alphatwirl.collector.ToTupleListWithDatasetColumn(
```
There might be other examples, although this is the first one I've noticed.  Would be nice to update this so that this repo serves as an up-to-date demo of using AlphaTwirl

**Comment by TaiSakuma** [comment]
Yes. That it true.
That is why alphatwirl is a submodule in this repo at the moment, so a commit in this repo can be associated with a specific commit in alphatwirl.
That is also why the version of alphatwirl is less than 1.0. The API hasn't been fixed.

**Comment by TaiSakuma** [comment]
i will close this. it was updated since this issue was open. then it is behind again. when it needs to be updated again, new issue should be opened.
